
service: serverless-auth-aws

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: eu-central-1

iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
      Resource: "*"

functions:
  getUser:
    handler: src/functions/getUser.getUser
    events:
      - http:
          method: get
          cors: true
          path: /v1/users/{ID}
  # validate:
  #   handler: src/functions/validate.validate
  # loginUser:
  #   handler: src/functions/loginUser.login
  #   events:
  #     - http:
  #         method: post
  #         cors: true
  #         path: /v1/users/login
          # request:
          #   schema:
          #     application/json: ${file(src/schema/login_request.json)}
  # createUser:
  #   handler: src/functions/createUser.createUser
  #   events:
  #     - http:
  #         method: post
  #         cors: true
  #         path: /v1/users
          # authorizer: validate
          # request:
          #   schema:
          #     application/json: ${file(src/schema/create_user_request.json)}

  

# plugins:
#   - serverless-pseudo-parameters
#   - serverless-mocha
custom:
  serverless-mocha-plugin:
    testTemplate: templates/testTemplate.ejs
    functionTemplate: templates/functionTemplate.ejs
